DOCKER_AUTH: &DOCKER_AUTH
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASS
version: 2.1
orbs:
  docker: circleci/docker@1.4.0

jobs:
  build_phan:
    working_directory: ~/docker
    environment:
      BUILDKIT_PROGRESS: plain
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - add_ssh_keys
      - docker/install-docker
      - run:
          name: "Authorize docker"
          command: |
            bash .ops/docker_auth.sh
      - run:
          name: "Build image and update docker image"
          command: |
            bash .ops/build_and_push_docker_image.sh php
  build_php:
    working_directory: ~/docker
    environment:
      BUILDKIT_PROGRESS: plain
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - add_ssh_keys
      - docker/install-docker
      - run: 
          name: "Authorize docker"
          command: |
            bash .ops/docker_auth.sh
      - run:
          name: "Build image and update docker image"
          command: |
            bash .ops/build_and_push_docker_image.sh php
  build_circleci:
    working_directory: ~/docker
    environment:
      BUILDKIT_PROGRESS: plain
      DOCKER_BUILDKIT: "1"
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - add_ssh_keys
      - docker/install-docker
      - run: 
          name: "Authorize docker"
          command: |
            bash .ops/docker_auth.sh
      - run:
          name: "Build image and update docker image"
          working_directory: "~/docker/circleci-ext/"
          command: |
            bash build.sh
workflows:
  version: 2
  docker_images:
    jobs:
      - build_circleci:
          context:
            - docker_auth
      - build_php:
          context:
            - docker_auth
      - build_phan:
          context:
            - docker_auth
  build-nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters: 
            branches:
              only:
                - /master/
    jobs:
      - build_php:
          context:
            - docker_auth
      - build_circleci:
          context:
            - docker_auth
      - build_phan:
          context:
            - docker_auth
        
        
