DOCKER_AUTH: &DOCKER_AUTH
  auth:
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASS
version: 2.1
orbs:
  docker: circleci/docker@1.4.0

jobs:
  build_docker:
    working_directory: ~/docker
    environment:
      IMAGE_NAME: byflou/php
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - add_ssh_keys
      - docker/install-docker
      - run:
          name: "Build image and update docker image"
          command: |
            bash .ops/build_and_push_docker_image.sh php
workflows:
  version: 2
  docker_images:
    jobs:
      - build_docker
  build-nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
    jobs:
      - build_docker
        
        
